working-directory: 'workdir'

document-list:
  - name: "kodo-import"
    url: 'https://developer.qiniu.com/kodo/6435/kodoimport'
    after-inferencer-checkers: [ 'kodoImportVersionChecker' ]


  - name: "kodo-browser"
    url: 'https://developer.qiniu.com/kodo/5972/kodo-browser'
    after-inferencer-checkers: [ 'kodoBrowserVersionChecker' ]

  - name: "qshell"
    url: 'https://developer.qiniu.com/kodo/1302/qshell'
    after-inferencer-checkers: [ 'qshellVersionChecker' ]

user-agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'

logger:
  level: 'INFO'
  show-stack-trace: false